name: "Post-Exploitation Scenario"
description: "Lateral movement and persistence testing"
version: "1.0"
author: "mooncakesg"

red_team:
  - module: "post_exploitation"
    technique: "lateral_movement"
    target: "192.168.1.100"
    parameters:
      techniques: ["smb", "wmi", "rdp"]
      target_ports: [445, 135, 3389]
  
  - module: "post_exploitation"
    technique: "persistence"
    target: "192.168.1.100"
    parameters:
      techniques: ["registry", "scheduled_task", "startup"]
      persistence_type: "user"

blue_team:
  - module: "system_monitoring"
    detection: "lateral_movement_detection"
    sources: ["system_logs", "network_logs"]
  
  - module: "process_monitoring"
    detection: "suspicious_process_detection"
    sources: ["process_logs", "sysmon_logs"]
  
  - module: "registry_monitoring"
    detection: "registry_modification_detection"
    sources: ["registry_logs", "sysmon_logs"]

purple_logic:
  correlation_rules:
    - attack: "lateral_movement"
      expected_detection: "lateral_movement_detection"
      mitre_technique: "T1021"
    
    - attack: "persistence"
      expected_detection: "registry_modification_detection"
      mitre_technique: "T1053"

safety:
  sandbox_mode: true
  rate_limiting: true
  confirmation_required: true
  max_targets: 5
  timeout: 900
